
CREATE TABLE
	HR.EMPLOYEES (
		/*
        *   UNIQUE FILDS
        */
		ID_EMPLOYEE UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
		/*
		*  EMPLOYEE DATA WHERE WE WILL SPECIFY 
		*  THE EMPLOYEE'S PERSONAL INFORMATION
		*/
		EMPLOYEE_CODE VARCHAR(25),
		FIRST_NAME VARCHAR(100) NOT NULL,
		LAST_NAME VARCHAR(100) NOT NULL,
		STATUS CHARACTER(1) NOT NULL DEFAULT 'A'::BPCHAR,
		GENDER CHARACTER(1),
		BIRTH_DATE DATE,
		CIVIL_STATUS VARCHAR(25),
		ADDRESS VARCHAR(300),
		PHONE VARCHAR(100),
		CELLPHONE VARCHAR(100),
		BLOOD_TYPE VARCHAR(25),
		EMAIL VARCHAR(100),
		ID_BANK UUID,
		ACCOUNT_BANK VARCHAR(50),
		ACCOUNT_TYPE VARCHAR(50),
		DRIVER_LICENSE BOOLEAN DEFAULT false,
		DUI VARCHAR(25),
		NIT VARCHAR(25),
		ISSS VARCHAR(25),
		NUP VARCHAR(25),
		ID_DEPARTMENT UUID,
		ID_MUNICIPALITY UUID,
		/*
		*  EMPLOYEE POSITION DATA
		*  IN THESE FIELDS WE WILL SPECIFY
		*  THE INFORMATION OF THE EMPLOYEE IN THE COMPANY
		*/
		POSITION VARCHAR(100),
		ADMISSION_DATE DATE DEFAULT CURRENT_DATE,
		RETIREMENT BOOLEAN DEFAULT false,
		RETIREMENT_DATE DATE,
		DISMISSAL BOOLEAN DEFAULT false,
		DISMISSAL_DATE DATE,
		RESIGNATION BOOLEAN DEFAULT false,
		RESIGNATION_DATE DATE,
		MONTHLY_SALARY NUMERIC(10, 4) DEFAULT 0.00,
		DAILY_SALARY NUMERIC(12, 4) DEFAULT 0.00,
		HOUR_WAGE NUMERIC(10, 4) DEFAULT 0.00,
		CONTRACT_DATE DATE,
		ID_ORGANIZATIONAL_UNIT UUID,
		/*
		*  FIELDS TO CONDUCT AUDIT OF THE DATABASE
		*  THESE FIELDS ALLOW US TO KEEP CONTROL OF THE
		*  USERS WHO INTERACT WITH IT AND KNOW WHO
		*  ENTER OR UPDATE INFORMATION.
		*/
		ID_USER_CREATION UUID,
		ID_USER_UPDATE UUID,
		USER_BD VARCHAR(100) DEFAULT CURRENT_USER,
		CREATION_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_DATE,
		UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
	)

-- Foreign key restriction for ID_USER_CREATION
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_USER_CREATION FOREIGN KEY (ID_USER_CREATION) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;

-- Foreign key restriction for ID_USER_UPDATE
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_USER_UPDATE FOREIGN KEY (ID_USER_UPDATE) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;

-- Foreign key restriction for ID_DEPARTMENT
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_DEPARTMENT FOREIGN KEY (ID_DEPARTMENT) REFERENCES GT.DEPARTMENT(ID_DEPARTMENT) ON DELETE NO ACTION;

-- Foreign key restriction for ID_MUNICIPALITY
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_MUNICIPALITY FOREIGN KEY (ID_MUNICIPALITY) REFERENCES GT.MUNICIPALITY(ID_MUNICIPALITY) ON DELETE NO ACTION;

-- Foreign key restriction for ID_BANK
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_BANK FOREIGN KEY (ID_BANK) REFERENCES GT.BANK(ID_BANK) ON DELETE NO ACTION;

-- Foreign key restriction for ID_ORGANIZATIONAL_UNIT
ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT FK_ID_ORGANIZATIONAL_UNIT FOREIGN KEY (ID_ORGANIZATIONAL_UNIT) REFERENCES HR.ORGANIZATIONAL_UNIT(ID_ORGANIZATIONAL_UNIT) ON DELETE NO ACTION;