
CREATE TABLE
	HR.PARAMETERS_HOUR (
		/*
		*	UNIQUE FILD
		*/
		ID_PARAMETERS UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
		/*
		*	FIXED FIELDS
		*/
		DAY_CODE VARCHAR(10),
		DAY_NAME VARCHAR(100),
		ENTRY_TIME TIME,
		DEPARTURE_TIME TIME,
		/*
		*	FIELDS TO CONDUCT AUDIT OF THE DATABASE
		*	THESE FIELDS ALLOW US TO KEEP CONTROL OF THE
		*	USERS WHO INTERACT WITH IT AND KNOW WHO
		*	ENTER OR UPDATE INFORMATION.
		*/
		ID_USER_CREATION UUID,
		ID_USER_UPDATE UUID,
		USER_BD VARCHAR(100) DEFAULT CURRENT_USER,
		CREATION_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
		UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
	)

-- Foreign key restriction for ID_USER_CREATION
ALTER TABLE HR.PARAMETERS_HOUR
ADD CONSTRAINT FK_ID_USER_CREATION FOREIGN KEY (ID_USER_CREATION) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;

-- Foreign key restriction for ID_USER_UPDATE
ALTER TABLE HR.PARAMETERS_HOUR
ADD CONSTRAINT FK_ID_USER_UPDATE FOREIGN KEY (ID_USER_UPDATE) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;
