
CREATE TABLE
	HR.PAYMENT_SHEET_DETAIL (
        /*
        *   UNIQUE FILD
        */
        PAYMENT_SHEET_DETAIL UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
		/*
		*   EMPLOYEE'S KEY WHERE WE SPECIFY THE 
        *   EMPLOYEE'S PERSONAL INFORMATION
		*/
        ID_EMPLOYEE UUID,
        /*
        *   THESE FIELDS STORE ALL OF AN EMPLOYEE'S EARNINGS
        *   OVER A PERIOD OF TIME.
        */
        EMPLOYEE_SALARY NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_EXTRA_HOURS NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_EXTRA_SHIFT NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_OTHER_INCOME NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_VACATIONS NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_HOLIDAY NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_AGUINALDO NUMERIC(12, 4) DEFAULT 0.00,
        /*
        *   THESE FIELDS STORE ALL OF AN EMPLOYEE'S DISCOUNTS
        *   OVER A PERIOD OF TIME.
        */
        EMPLOYEE_ISSS NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_AFP NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_IPSFA NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_ISR NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYEE_OTHER_DISCOUNTS NUMERIC(12, 4) DEFAULT 0.00,
        /*
        *   THESE FIELDS STORE AN EMPLOYER CONTRIBUTIONS OVER
        *   PERIOD OF TIME.
        */
        EMPLOYER_ISSS NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYER_AFP NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYER_IPSFA NUMERIC(12, 4) DEFAULT 0.00,
        EMPLOYER_INSAFORP NUMERIC(12, 4) DEFAULT 0.00,
		/*
		*   FIELDS TO CONDUCT AUDIT OF THE DATABASE
		*   THESE FIELDS ALLOW US TO KEEP CONTROL OF THE
		*   USERS WHO INTERACT WITH IT AND KNOW WHO
		*   ENTER OR UPDATE INFORMATION.
		*/
		ID_USER_CREATION UUID,
		ID_USER_UPDATE UUID,
		USER_BD VARCHAR(100) DEFAULT CURRENT_USER,
		CREATION_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
		UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
	)

-- Foreign key restriction for ID_USER_CREATION
ALTER TABLE HR.PAYMENT_SHEET_DETAIL
ADD CONSTRAINT FK_ID_USER_CREATION FOREIGN KEY (ID_USER_CREATION) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;

-- Foreign key restriction for ID_USER_UPDATE
ALTER TABLE HR.PAYMENT_SHEET_DETAIL
ADD CONSTRAINT FK_ID_USER_UPDATE FOREIGN KEY (ID_USER_UPDATE) REFERENCES GT.USERS(ID_USER) ON DELETE NO ACTION;

-- Foreign key restriction for ID_EMPLOYEE
ALTER TABLE HR.PAYMENT_SHEET_DETAIL
ADD CONSTRAINT FK_ID_EMPLOYEE FOREIGN KEY (ID_EMPLOYEE) REFERENCES HR.EMPLOYEES(ID_EMPLOYEE) ON DELETE NO ACTION;
