
CREATE TABLE
	GT.USERS (
		/*
        *   UNIQUE FILDS
        */
		ID_USER UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
		USER_CODE VARCHAR(100) UNIQUE,
		USER_NAME VARCHAR(100),
		USER_PASSWORD VARCHAR(500),
		ACTIVE BOOLEAN DEFAULT TRUE,
		/*
		*  FIELDS TO CONDUCT AUDIT OF THE DATABASE
		*  THESE FIELDS ALLOW US TO KEEP CONTROL OF THE
		*  USERS WHO INTERACT WITH IT AND KNOW WHO
		*  ENTER OR UPDATE INFORMATION.
		*/
		USER_CREATION UUID,
		USER_UPDATE UUID,
		USER_BD VARCHAR(100) DEFAULT CURRENT_USER,
		CREATION_DATE TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
		UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE
	)